env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'
  import/prefer-default-export: 'off'
  react/jsx-filename-extension: [2, { 'extensions': ['.jsx', '.tsx'] }]
  react/require-default-props: 'off'
